### ISSUE TITLE
SystemError when importing Ecole 0.5.0

### ISSUE THREAD

**Issue by juditacs** [conda-forge/ecole-feedstock#6]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Ecole 0.5.0 installs successfully but I'm unable to import it. I created the conda environment yesterday and I only installed PyTorch aside from Ecole.

```
$ python -c 'import ecole'                          
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$HOME/miniconda3/envs/test1/lib/python3.8/site-packages/ecole/__init__.py", line 3, in <module>
    from ecole.core import RandomEngine, seed, spawn_random_engine, Exception
ImportError: SystemError: <built-in method __contains__ of dict object at 0x7fc652e6e900> returned a result with an error set
```

<br/>
Environment (<code>conda list</code>):

```
$ conda list
# packages in environment at $HOME/miniconda3/envs/test1:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
ampl-mp                   3.1.0             h616b090_1004    conda-forge
blas                      1.0                         mkl  
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cppad                     20210000.5           h9c3ff4c_0    conda-forge
cudatoolkit               11.1.1               h6406543_8    conda-forge
ecole                     0.5.0            py38h80b8489_1    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
fmt                       7.1.3                h0efe328_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
ipopt                     3.13.4               h7ede334_0    conda-forge
jpeg                      9b                   h024ee3a_2  
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libblas                   3.9.0                     8_mkl    conda-forge
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.1.0                h2733197_1  
libuv                     1.41.0               h7f98852_0    conda-forge
llvm-openmp               11.0.1               h4bd325d_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
mkl-service               2.3.0            py38h1e0a361_2    conda-forge
mkl_fft                   1.3.0            py38h5c078b8_1    conda-forge
mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
mumps-include             5.2.1               ha770c72_10    conda-forge
mumps-seq                 5.2.1               h47a8eb5_10    conda-forge
ncurses                   6.2                  he6710b0_1  
nettle                    3.6                  he412f7d_0    conda-forge
ninja                     1.10.2               h4bd325d_0    conda-forge
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   1.1.1j               h7f98852_0    conda-forge
pillow                    8.1.2            py38he98fc37_0  
pip                       21.0.1           py38h06a4308_0  
python                    3.8.8                hdb3f193_4  
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
readline                  8.1                  h27cfd23_0  
scip                      7.0.2                h9e5b675_3    conda-forge
scotch                    6.0.9                h0eec0ba_1    conda-forge
setuptools                52.0.0           py38h06a4308_0  
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h62c20be_0  
tbb                       2020.2               h4bd325d_4    conda-forge
tk                        8.6.10               hbc83047_0  
torchaudio                0.8.0                      py38    pytorch
torchvision               0.9.0                py38_cu111    pytorch
typing_extensions         3.7.4.3                    py_0    conda-forge
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                ha95c52a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test1
    active env location : $HOME/miniconda3/envs/test1
            shell level : 2
       user config file : $HOME/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.2=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : $HOME/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : $HOME/miniconda3/pkgs
                          $HOME/.conda/pkgs
       envs directories : $HOME/miniconda3/envs
                         $HOME/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.5 Linux/5.4.0-56-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 722800004:722800004
             netrc file : None
           offline mode : False

```
</details>

**Comment by juditacs** [comment]
I just tried it with two other fresh environments and I get the same error.

1. Python 3.8, CUDA 10.2
22. Python 3.7, CUDA 10.2

**Comment by AntoinePrv** [comment]
Thanks @juditacs. It looks like this may be a cross-channel problem: mixing packages from `default`, `conda-forge`, and `pytorch` channels.
While it should be feasible, I'm not surprised to see errors.

I still have no errors using packages from `pytorch` and `conda-forge`.
As for `defaults` channel, I am personally not using it. All their packages, and much more, are available in the `conda-forge` channel.

To do that, you can:
```bash
conda config --add channels conda-forge
conda config --set channel_priority strict
```
Then both
```bash
conda create -n envname -c conda-forge pytorch ecole
```
```bash
conda create -n envname -c pytorch -c conda-forge pytorch ecole
```
work well for me.

_Note_: I'm on my Mac with no GPU, so this is still a first guess. Let us know if it works.

**Comment by juditacs** [comment]
This indeed fixes the issue. Thanks for the help.
